blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: security@palletsprojects.com
    about: Do not report security issues publicly. Email our security contact.
  - name: Questions
    url: https://stackoverflow.com/questions/tagged/Jinja?tab=Frequent
    about: Search for and ask questions about your code on Stack Overflow.
  - name: Questions and discussions
    url: https://discord.gg/t6rrQZH
    about: Discuss questions about your code on our Discord chat.
